package day42_Exceptions;

public class ThrowsKeyword2 {
    public static void main(String[] args) throws ArithmeticException{
        System.out.println("______________Test Started____________");

        System.out.println(8/0);

        System.out.println("______________Test Complited____________");





    }
}
